add modern_botok with a new dictionary.
Esukhia/botok-data pull request #2
Opened 2024-11-29 15:36 UTC by ykyogoku

The dictionary is compiled from various dictionaries taken from Christian Steinert's repo and adds support for modern Tibetan language

2024-11-29 15:42 UTC, eroux requested changes
thanks @ykyogoku ! A few things:
- can you add a README.md file in the dialect_packs/modern_botok/ directory with some background on the files? (acknowledging the project, contributors, etc.)
- can you update the main README and add references to this new dialeck_pack, with a link to the more detailed README?

2024-12-03 15:39 UTC, eroux approved these changes

2024-12-03 15:39 UTC, eroux commented on dialect_packs/modern_botok/README.md
> +Botok out-of-the-box can tokenize classical Tibetan text or traditional genres, however since it depends on a dictionary for tokenization, lacks capabilities for modern Tibetan, in particular, the la
this seems a bit out of place, please remove

2024-12-03 15:39 UTC, eroux commented on dialect_packs/modern_botok/README.md
> +## Copyright
Please replace with "acknowledgement"

2024-12-03 15:39 UTC, eroux commented on dialect_packs/modern_botok/README.md
> +Please acknowledge the project in any use of these materials. Copyright for the project resides with the two universities.
please remove "copyright for the project...", I'm not sure what that even means... I doubt SOAS owns the copyright on the Tsik mdzod chen mo

2024-12-03 15:39 UTC, eroux commented on dialect_packs/modern_botok/README.md
>  Please acknowledge the project in any use of these materials. Copyright for the project resides with the two universities.
@fxerhard can you also remove this?

2024-12-03 15:48 UTC, fxerhard commented on dialect_packs/modern_botok/README.md
> +Botok out-of-the-box can tokenize classical Tibetan text or traditional genres, however since it depends on a dictionary for tokenization, lacks capabilities for modern Tibetan, in particular, the la
removed the two paragraphs

2024-12-03 15:54 UTC, fxerhard commented on dialect_packs/modern_botok/README.md
>  Please acknowledge the project in any use of these materials. Copyright for the project resides with the two universities.
done so

2024-12-03 15:55 UTC, fxerhard commented on dialect_packs/modern_botok/README.md
> +Please acknowledge the project in any use of these materials. Copyright for the project resides with the two universities.
copyright removed

2024-12-03 15:55 UTC, fxerhard commented on dialect_packs/modern_botok/README.md
> +## Copyright
done

2024-12-03 16:16 UTC, merged